"""drop unique constraint on site_acronyms

Revision ID: 070067d91702
Revises: 4eef9566168c
Create Date: 2026-04-03 11:45:58.475120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070067d91702'
down_revision = '4eef9566168c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('site_GU'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('site_GU'), ['site_acronyms'], unique=True)

    # ### end Alembic commands ###
