"""remove ticket title ticket_content ticket_attachment tables

Revision ID: 13e58200527c
Revises: bf82b7464861
Create Date: 2026-09-09 20:13:08.035772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e58200527c'
down_revision = 'bf82b7464861'
branch_labels = None
depends_on = None


def upgrade():
    # Drop order matters on MySQL, which enforces FK constraints at DDL time
    # (unlike the disposable SQLite file this migration was first verified
    # against, whose scratch baseline didn't declare real FK constraints):
    # ticket_content/ticket_attachment reference ticket, and ticket
    # references title, so children must drop before their parents.
    op.drop_table('ticket_content')
    op.drop_table('ticket_attachment')
    op.drop_table('ticket')
    op.drop_table('title')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_content',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('ticket_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('cnt_created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('title_id', sa.INTEGER(), nullable=False),
    sa.Column('tck_status', sa.VARCHAR(length=45), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('site_id', sa.INTEGER(), nullable=False),
    sa.Column('assigned_to_id', sa.INTEGER(), nullable=True),
    sa.Column('escalated', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_attachment',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('ticket_id', sa.INTEGER(), nullable=False),
    sa.Column('attach_image', sa.VARCHAR(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('title',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('title_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
