"""add work order labor material and cost record tables

Revision ID: 18f317e4f1a5
Revises: a370d33e0db2
Create Date: 2026-09-07 19:24:57.306562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f317e4f1a5'
down_revision = 'a370d33e0db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('material_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vendor_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_id')
    )
    op.create_table('work_order_labor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('labor_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('labor_type', sa.String(length=30), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_labor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_labor_technician_id'), ['technician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_labor_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('work_order_material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_material_work_order_id'), ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_material_work_order_id'))

    op.drop_table('work_order_material')
    with op.batch_alter_table('work_order_labor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_labor_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_labor_technician_id'))

    op.drop_table('work_order_labor')
    op.drop_table('cost_record')
    # ### end Alembic commands ###
