"""add ftp schedule fields to organization

Revision ID: 1bb51a6176c9
Revises: c1c0a7bbb4ca
Create Date: 2026-03-22 16:57:24.803883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb51a6176c9'
down_revision = 'c1c0a7bbb4ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ftp_schedule_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ftp_schedule_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ftp_schedule_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ftp_schedule_days', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ftp_last_run_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ftp_last_run_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('ftp_last_run_status')
        batch_op.drop_column('ftp_last_run_at')
        batch_op.drop_column('ftp_schedule_days')
        batch_op.drop_column('ftp_schedule_minute')
        batch_op.drop_column('ftp_schedule_hour')
        batch_op.drop_column('ftp_schedule_enabled')

    # ### end Alembic commands ###
