"""drop unique constraint on site_cds and site_code

Revision ID: 4eef9566168c
Revises: b2f9da811cd8
Create Date: 2026-04-01 21:53:29.405293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eef9566168c'
down_revision = 'b2f9da811cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('site_cds'))
        batch_op.drop_index(batch_op.f('site_code'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('site_code'), ['site_code'], unique=True)
        batch_op.create_index(batch_op.f('site_cds'), ['site_cds'], unique=True)

    # ### end Alembic commands ###
