"""add ftp fields to organization drop ftp tables

Revision ID: 6d209b9fc49c
Revises: 9c1f318f3a7a
Create Date: 2026-03-22 12:22:00.856093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d209b9fc49c'
down_revision = '9c1f318f3a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ftp_connection')
    op.drop_table('ftp_schedule')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ftp_host', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ftp_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ftp_username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ftp_password_enc', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('ftp_path', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('ftp_use_tls', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('ftp_use_tls')
        batch_op.drop_column('ftp_path')
        batch_op.drop_column('ftp_password_enc')
        batch_op.drop_column('ftp_username')
        batch_op.drop_column('ftp_port')
        batch_op.drop_column('ftp_host')

    op.create_table('ftp_schedule',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ftp_host', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ftp_port', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ftp_username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ftp_password_enc', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('ftp_path', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('use_tls', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('schedule_hour', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schedule_minute', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schedule_days', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_by_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_run_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_run_status', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('ftp_schedule_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ftp_connection',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ftp_host', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ftp_port', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ftp_username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ftp_password_enc', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('ftp_path', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('use_tls', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_by_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('ftp_connection_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
