"""remove site_abb from site

Revision ID: 8f7faa338f50
Revises: 1bb51a6176c9
Create Date: 2026-03-25 20:15:08.191556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f7faa338f50'
down_revision = '1bb51a6176c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('site_abb'))
        batch_op.drop_column('site_abb')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_abb', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_index(batch_op.f('site_abb'), ['site_abb'], unique=True)

    # ### end Alembic commands ###
