"""add ftp_schedule table

Revision ID: 9c145fa43d80
Revises: b47d77fd2576
Create Date: 2026-03-21 20:12:20.554991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c145fa43d80'
down_revision = 'b47d77fd2576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ftp_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('ftp_host', sa.String(length=255), nullable=False),
    sa.Column('ftp_port', sa.Integer(), nullable=False),
    sa.Column('ftp_username', sa.String(length=255), nullable=False),
    sa.Column('ftp_password_enc', sa.String(length=512), nullable=False),
    sa.Column('ftp_path', sa.String(length=512), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('schedule_hour', sa.Integer(), nullable=False),
    sa.Column('schedule_minute', sa.Integer(), nullable=False),
    sa.Column('schedule_days', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ftp_schedule')
    # ### end Alembic commands ###
