"""add ftp_connection table

Revision ID: 9c1f318f3a7a
Revises: 9c145fa43d80
Create Date: 2026-03-22 10:29:12.644559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1f318f3a7a'
down_revision = '9c145fa43d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ftp_connection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ftp_host', sa.String(length=255), nullable=False),
    sa.Column('ftp_port', sa.Integer(), nullable=False),
    sa.Column('ftp_username', sa.String(length=255), nullable=False),
    sa.Column('ftp_password_enc', sa.String(length=512), nullable=False),
    sa.Column('ftp_path', sa.String(length=512), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ftp_connection')
    # ### end Alembic commands ###
