"""add must_change_password to user

Revision ID: b47d77fd2576
Revises: 
Create Date: 2026-02-25 20:03:41.142887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47d77fd2576'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulk_upload_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bulk_upload_log_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['uploaded_by_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('bulk_upload_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bulk_upload_log_ibfk_1'), 'user', ['uploaded_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
