"""add maintenance plan and schedule tables

Revision ID: bc1779acd4f1
Revises: cb141050cfff
Create Date: 2026-09-07 18:28:29.995378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1779acd4f1'
down_revision = 'cb141050cfff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_type_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('custom_interval_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('assigned_team', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(asset_id IS NOT NULL AND asset_type_id IS NULL) OR (asset_id IS NULL AND asset_type_id IS NOT NULL)', name='ck_maintenance_plan_single_target'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['priority.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_plan_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_plan_asset_type_id'), ['asset_type_id'], unique=False)

    op.create_table('maintenance_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maintenance_plan_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('last_generated_at', sa.DateTime(), nullable=True),
    sa.Column('last_work_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_work_order_id'], ['work_order.id'], ),
    sa.ForeignKeyConstraint(['maintenance_plan_id'], ['maintenance_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('maintenance_plan_id', 'asset_id', name='uq_maintenance_schedule_plan_asset')
    )
    with op.batch_alter_table('maintenance_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_schedule_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_schedule_maintenance_plan_id'), ['maintenance_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_schedule_next_due_date'), ['next_due_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_schedule_next_due_date'))
        batch_op.drop_index(batch_op.f('ix_maintenance_schedule_maintenance_plan_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_schedule_asset_id'))

    op.drop_table('maintenance_schedule')
    with op.batch_alter_table('maintenance_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_plan_asset_type_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_plan_asset_id'))

    op.drop_table('maintenance_plan')
    # ### end Alembic commands ###
