"""add site city state zip and principal contact fields

Revision ID: bf82b7464861
Revises: 6d752033cb01
Create Date: 2026-09-09 18:41:14.792019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf82b7464861'
down_revision = '6d752033cb01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('site_state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('site_zip', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('principal_first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('principal_last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('principal_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('principal_phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('principal_phone')
        batch_op.drop_column('principal_email')
        batch_op.drop_column('principal_last_name')
        batch_op.drop_column('principal_first_name')
        batch_op.drop_column('site_zip')
        batch_op.drop_column('site_state')
        batch_op.drop_column('site_city')

    # ### end Alembic commands ###
