"""encrypt ftp host and username in organization

Revision ID: c1c0a7bbb4ca
Revises: 6d209b9fc49c
Create Date: 2026-03-22 14:05:48.787436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1c0a7bbb4ca'
down_revision = '6d209b9fc49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ftp_host_enc', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('ftp_username_enc', sa.String(length=512), nullable=True))
        batch_op.drop_column('ftp_username')
        batch_op.drop_column('ftp_host')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ftp_host', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('ftp_username', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('ftp_username_enc')
        batch_op.drop_column('ftp_host_enc')

    # ### end Alembic commands ###
