"""add sla rule notification preference notification log and csv import log tables

Revision ID: c419b2165ce3
Revises: d919f88115eb
Create Date: 2026-09-08 06:54:21.691718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c419b2165ce3'
down_revision = 'd919f88115eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('response_hours', sa.Integer(), nullable=False),
    sa.Column('resolution_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('response_hours > 0 AND resolution_hours > 0', name='ck_sla_rule_positive_hours'),
    sa.ForeignKeyConstraint(['priority_id'], ['priority.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority_id')
    )
    op.create_table('csv_import_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('duplicate_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'entity_type', 'entity_id', 'bucket', 'user_id', name='uq_notification_dedup')
    )
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_log_event_type'), ['event_type'], unique=False)

    op.create_table('notification_preference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pm_due', sa.Boolean(), nullable=False),
    sa.Column('pm_overdue', sa.Boolean(), nullable=False),
    sa.Column('inspection_due', sa.Boolean(), nullable=False),
    sa.Column('inspection_failed', sa.Boolean(), nullable=False),
    sa.Column('vendor_contract_expiring', sa.Boolean(), nullable=False),
    sa.Column('asset_warranty_expiring', sa.Boolean(), nullable=False),
    sa.Column('sla_warning', sa.Boolean(), nullable=False),
    sa.Column('sla_breach', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_preference')
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_log_event_type'))

    op.drop_table('notification_log')
    op.drop_table('csv_import_log')
    op.drop_table('sla_rule')
    # ### end Alembic commands ###
