"""add work order priority category tables

Revision ID: cb141050cfff
Revises: f11aade72780
Create Date: 2026-09-07 18:19:41.995417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb141050cfff'
down_revision = 'f11aade72780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('priority',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_subcategory_category_name')
    )
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subcategory_category_id'), ['category_id'], unique=False)

    op.create_table('work_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wo_number', sa.String(length=20), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('assigned_team', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['priority_id'], ['priority.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wo_number')
    )
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_priority_id'), ['priority_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_status'), ['status'], unique=False)

    op.create_table('work_order_attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('attach_file', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_order_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_comment_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('work_order_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_status_history_work_order_id'), ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_status_history_work_order_id'))

    op.drop_table('work_order_status_history')
    with op.batch_alter_table('work_order_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_comment_work_order_id'))

    op.drop_table('work_order_comment')
    op.drop_table('work_order_attachment')
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_status'))
        batch_op.drop_index(batch_op.f('ix_work_order_source'))
        batch_op.drop_index(batch_op.f('ix_work_order_site_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_room_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_requester_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_priority_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_facility_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_due_date'))
        batch_op.drop_index(batch_op.f('ix_work_order_created_at'))
        batch_op.drop_index(batch_op.f('ix_work_order_category_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_assigned_to_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_asset_id'))

    op.drop_table('work_order')
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcategory_category_id'))

    op.drop_table('subcategory')
    op.drop_table('priority')
    op.drop_table('category')
    # ### end Alembic commands ###
