"""add project tables and asset work order project links

Revision ID: cf427a9e2830
Revises: 18f317e4f1a5
Create Date: 2026-09-07 19:47:56.352841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf427a9e2830'
down_revision = '18f317e4f1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_site_id'), ['site_id'], unique=False)

    op.create_table('project_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('cost_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('incurred_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_cost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_cost_project_id'), ['project_id'], unique=False)

    op.create_table('project_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('attach_file', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_task_project_id'), ['project_id'], unique=False)

    op.create_table('project_vendor',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'vendor_id')
    )
    # Adding a column-with-new-FK to an EXISTING table forces SQLite's batch
    # mode into a full table recreate, which requires every one of the
    # table's pre-existing constraints to be reflectable with a name — ours
    # aren't. Verified in Phase 6 (see application/CLAUDE.md) that this is
    # SQLite-specific: MySQL (production) handles a plain
    # ADD COLUMN ... ADD CONSTRAINT with no recreate needed. So the columns
    # go in everywhere; the DB-level FK constraint only on non-SQLite.
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('safety_impact', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('operational_importance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_asset_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_work_order_project_id'), ['project_id'], unique=False)

    if op.get_bind().dialect.name != 'sqlite':
        with op.batch_alter_table('asset', schema=None) as batch_op:
            batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'], ondelete='SET NULL')
        with op.batch_alter_table('work_order', schema=None) as batch_op:
            batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    if op.get_bind().dialect.name != 'sqlite':
        with op.batch_alter_table('work_order', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='foreignkey')
        with op.batch_alter_table('asset', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_project_id'))
        batch_op.drop_column('project_id')
        batch_op.drop_column('operational_importance')
        batch_op.drop_column('safety_impact')

    op.drop_table('project_vendor')
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_task_project_id'))

    op.drop_table('project_task')
    op.drop_table('project_document')
    with op.batch_alter_table('project_cost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_cost_project_id'))

    op.drop_table('project_cost')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_site_id'))

    op.drop_table('project')
    # ### end Alembic commands ###
