"""add work_order completed_at index

Revision ID: d919f88115eb
Revises: cf427a9e2830
Create Date: 2026-09-07 20:26:00.337090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd919f88115eb'
down_revision = 'cf427a9e2830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_completed_at'), ['completed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_completed_at'))

    # ### end Alembic commands ###
