"""add inspection tables

Revision ID: e7efb8ead9da
Revises: bc1779acd4f1
Create Date: 2026-09-07 18:50:50.872789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7efb8ead9da'
down_revision = 'bc1779acd4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['priority.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('inspection_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['inspection_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_item_template_id'), ['template_id'], unique=False)

    op.create_table('inspection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('generated_work_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(CASE WHEN facility_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN room_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN asset_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_inspection_single_target'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_work_order_id'], ['work_order.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['inspection_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_template_id'), ['template_id'], unique=False)

    op.create_table('inspection_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('inspection_item_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("result IN ('Pass', 'Fail', 'Needs Attention')", name='ck_inspection_result_value'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_item_id'], ['inspection_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id', 'inspection_item_id', name='uq_inspection_result_item')
    )
    with op.batch_alter_table('inspection_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_result_inspection_id'), ['inspection_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_result_inspection_id'))

    op.drop_table('inspection_result')
    with op.batch_alter_table('inspection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_template_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_site_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_room_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_facility_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_due_date'))
        batch_op.drop_index(batch_op.f('ix_inspection_asset_id'))

    op.drop_table('inspection')
    with op.batch_alter_table('inspection_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_item_template_id'))

    op.drop_table('inspection_item')
    op.drop_table('inspection_template')
    # ### end Alembic commands ###
