"""add ftp schedule start/stop dates to organization

Revision ID: f0a9192f6bd2
Revises: b563253a4f19
Create Date: 2026-04-08 19:03:33.001628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a9192f6bd2'
down_revision = 'b563253a4f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ftp_schedule_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ftp_schedule_stop_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('ftp_schedule_stop_date')
        batch_op.drop_column('ftp_schedule_start_date')

    # ### end Alembic commands ###
