"""add asset and asset condition tables

Revision ID: f11aade72780
Revises: 7d40fabd6b8b
Create Date: 2026-09-07 18:07:37.324881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11aade72780'
down_revision = '7d40fabd6b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('expected_life_years', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('asset_type_id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model_number', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('warranty_expiration', sa.Date(), nullable=True),
    sa.Column('expected_life_years', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('condition_score', sa.Integer(), nullable=True),
    sa.Column('condition_label', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_tag')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_asset_type_id'), ['asset_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_site_id'), ['site_id'], unique=False)

    op.create_table('asset_condition_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('assessed_at', sa.Date(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_asset_condition_score_range'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspector_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_condition_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_condition_history_assessed_at'), ['assessed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_condition_history_asset_id'), ['asset_id'], unique=False)

    op.create_table('asset_attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('condition_history_id', sa.Integer(), nullable=True),
    sa.Column('attach_file', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['condition_history_id'], ['asset_condition_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_attachment')
    with op.batch_alter_table('asset_condition_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_condition_history_asset_id'))
        batch_op.drop_index(batch_op.f('ix_asset_condition_history_assessed_at'))

    op.drop_table('asset_condition_history')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_site_id'))
        batch_op.drop_index(batch_op.f('ix_asset_serial_number'))
        batch_op.drop_index(batch_op.f('ix_asset_room_id'))
        batch_op.drop_index(batch_op.f('ix_asset_facility_id'))
        batch_op.drop_index(batch_op.f('ix_asset_asset_type_id'))

    op.drop_table('asset')
    op.drop_table('asset_type')
    # ### end Alembic commands ###
